# Generated by Django 6.0 on 2025-12-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("pack_g", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentItemAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_assignments",
                        to="ops.department",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="department_assignments",
                        to="ops.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_at", models.DateTimeField()),
                ("pickup_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_headers",
                        to="ops.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_units", models.IntegerField()),
                (
                    "order_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ops.orderheader",
                    ),
                ),
                (
                    "product_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines_as_product",
                        to="ops.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_at", models.DateTimeField()),
                ("required_units", models.IntegerField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="ops.departmentitemassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_key", models.CharField(max_length=50)),
                ("planned_started_at", models.DateTimeField()),
                ("planned_finished_at", models.DateTimeField()),
                ("is_feasible", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="ops.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentItemAssignmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_units_per_parent_unit", models.IntegerField()),
                (
                    "child_department_item_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_child",
                        to="ops.departmentitemassignment",
                    ),
                ),
                (
                    "parent_department_item_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_parent",
                        to="ops.departmentitemassignment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "parent_department_item_assignment",
                            "child_department_item_assignment",
                        ),
                        name="uniq_department_item_assignment_component",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="departmentitemassignment",
            constraint=models.UniqueConstraint(
                fields=("department", "item"), name="uniq_department_item_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.UniqueConstraint(
                fields=("order_header", "product_item"), name="uniq_order_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("assignment", "pickup_at"), name="uq_task_assignment_pickup_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskplan",
            constraint=models.UniqueConstraint(
                fields=("task", "plan_key"), name="uq_taskplan_task_plankey"
            ),
        ),
    ]
