# Generated by Django 6.0 on 2025-12-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskplan",
            name="uq_taskplan_task_plankey",
        ),
        migrations.AlterField(
            model_name="taskplan",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="ops.task",
            ),
        ),
        migrations.RemoveField(
            model_name="taskplan",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="taskplan",
            name="plan_key",
        ),
        migrations.RemoveField(
            model_name="taskplan",
            name="reason",
        ),
    ]
