# Generated by Django 6.0 on 2025-12-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentItemAssignmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_units_per_parent_unit", models.IntegerField()),
                (
                    "child_department_item_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_child",
                        to="ops.departmentitemassignment",
                    ),
                ),
                (
                    "parent_department_item_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_parent",
                        to="ops.departmentitemassignment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "parent_department_item_assignment",
                            "child_department_item_assignment",
                        ),
                        name="uniq_department_item_assignment_component",
                    )
                ],
            },
        ),
    ]
