# Generated by Django 6.0 on 2025-12-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_departmentitemassignmentcomponent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_at", models.DateTimeField()),
                ("pickup_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_headers",
                        to="ops.customer",
                    ),
                ),
            ],
        ),
    ]
