# Generated by Django 6.0 on 2025-12-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0004_orderline"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_at", models.DateTimeField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_keys",
                        to="ops.departmentitemassignment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "pickup_at"), name="uniq_task_key"
                    )
                ],
            },
        ),
    ]
