# Generated by Django 6.0 on 2025-12-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0005_taskkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_units", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("todo", "todo"), ("done", "done")],
                        default="todo",
                        max_length=16,
                    ),
                ),
                (
                    "task_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task",
                        to="ops.taskkey",
                    ),
                ),
            ],
        ),
    ]
